/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prototype.skripsi;
import java.io.File;
import java.sql.Connection;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import login.mainMenu;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author IqbalChandraEssens
 */
public class Client extends javax.swing.JFrame {

    /**
     * Creates new form FormCLIENT
     */
    public Client() {
        initComponents();
        table_client();
        kosong();
        AutoNomor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        head = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        NAME = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        company_name = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        addres = new javax.swing.JTextArea();
        phone = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_client = new javax.swing.JTable();
        save = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        NAME1 = new javax.swing.JLabel();
        staff_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        CLEAR = new javax.swing.JButton();
        NAME3 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txtCari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        head.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/tritanu_head.png"))); // NOI18N
        head.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                headMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(head)
                .addContainerGap(295, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(head, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NAME.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        NAME.setText("COMPANY NAME");
        jPanel2.add(NAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 57, 103, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("PHONE");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 149, 50, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("ADDRES");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 140, 74, 32));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("EMAIL");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 99, 43, 23));
        jPanel2.add(company_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(567, 55, 190, -1));

        addres.setColumns(20);
        addres.setLineWrap(true);
        addres.setRows(3);
        addres.setTabSize(4);
        jScrollPane1.setViewportView(addres);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(567, 140, 195, 70));
        jPanel2.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 147, 170, -1));
        jPanel2.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 101, 170, -1));

        table_client.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        table_client.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_clientMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(table_client);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 299, 792, 128));

        save.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        save.setText("SAVE");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel2.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 240, -1, -1));

        edit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        edit.setText("EDIT");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        jPanel2.add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 240, -1, -1));

        delete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel2.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 240, -1, -1));

        NAME1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        NAME1.setText("STAFF NAME");
        jPanel2.add(NAME1, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 103, 103, -1));
        jPanel2.add(staff_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(567, 101, 190, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setText("CLIENT ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 0, -1, 49));

        CLEAR.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        CLEAR.setText("REFRESH");
        CLEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLEARActionPerformed(evt);
            }
        });
        jPanel2.add(CLEAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 240, -1, -1));

        NAME3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        NAME3.setText("ID CLIENT");
        jPanel2.add(NAME3, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 57, 103, -1));

        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });
        jPanel2.add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 55, 170, -1));
        jPanel2.add(txtCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 241, 130, -1));

        btnCari.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCari.setText("SEARCH");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        jPanel2.add(btnCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(685, 240, -1, -1));
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 445, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/oke/CETAK CLIENT.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 221, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
public void AutoNomor(){
         try{
//             Statement st;
//             ResultSet rs;
//             String sql;
             
//             sql ="SELECT * FROM tb_tahun_ajaran order by id_ta desc";
//             st=conn.createStatement();
//             rs=st.executeQuery(sql);
             String sql = "SELECT * FROM client ORDER BY id_client DESC";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
             if (res.next()) {
                 String kd = res.getString("id_client").substring(3);
                 String AN = "" + (Integer.parseInt(kd)+1);
                 String Nol = "";
//                 txt_nama.setText(kd);
                 
                if (AN.length()==1) {
                     Nol ="00";
                 }if (AN.length()==2) {
                     Nol ="0";
                 } if (AN.length()==3) {
                     Nol="";
                 }
                 txt_id.setText("CL_"+Nol+AN);
                 
             } else {
                 txt_id.setText("CL_001");
             }
         } catch (Exception e){
             JOptionPane.showMessageDialog(rootPane, e);
         }
     }
    
    
    
    
    
    private void CLEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLEARActionPerformed
        // TODO add your handling code here:
        kosong();
        table_client();
        save.setEnabled(true);
        edit.setEnabled(false);
        delete.setEnabled(false);
        AutoNomor();
    }//GEN-LAST:event_CLEARActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        int jawab;

        if ((jawab= JOptionPane.showConfirmDialog(null,"are you sure?" , "confirm", JOptionPane.YES_NO_OPTION))==0) {

            try {
                String sql ="delete from client where id_client='"+txt_id.getText()+"'";
                java.sql.Connection conn=(Connection)config.configDB();
                java.sql.PreparedStatement pst=conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(this, "berhasil di hapus");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
            table_client();
            kosong();

        }

    }//GEN-LAST:event_deleteActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // Edit Data
        try {
            String sql ="UPDATE client SET id_client = '"+ txt_id.getText()+"',company_name = '"+ company_name.getText()+"',staff_name = '"+ staff_name.getText()+"', email = '"+ email.getText()+"', phone = '"+ phone.getText()+"',addres = '"+ addres.getText()+"' WHERE  id_client = '"+ txt_id.getText()+"' ";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "data berhasil di edit");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Perubahan Data Gagal"+e.getMessage());
        }
        table_client();
        kosong();
    }//GEN-LAST:event_editActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed

        try {
            String sql = "INSERT INTO client VALUES ('"+txt_id.getText()+"','"+company_name.getText()+"','"+staff_name.getText()+"','"+email.getText()+"','"+phone.getText()+"','"+addres.getText()+"')";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        table_client();
        kosong();
    }//GEN-LAST:event_saveActionPerformed

    private void table_clientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_clientMouseClicked

        // menampilkan data kedalam form pengisian:
        
        int baris = table_client.rowAtPoint(evt.getPoint());
        
        String Id = table_client.getValueAt(baris, 0).toString();
        txt_id.setText(Id);
        
        String company = table_client.getValueAt(baris, 1).toString();
        company_name.setText(company);

        String staff = table_client.getValueAt(baris, 2).toString();
        staff_name.setText(staff);

        String emailSet = table_client.getValueAt(baris, 3).toString();
        email.setText(emailSet);

        String phoneSet = table_client.getValueAt(baris, 4).toString();
        phone.setText(phoneSet);

//        String phoneSet = table_client.getValueAt(baris, 4).toString();
//        phone.setText(phoneSet);
//        
        String alamat= table_client.getValueAt(baris, 5).toString();
        addres.setText(alamat);

        
            save.setEnabled(false);
        edit.setEnabled(true);
        delete.setEnabled(true);
        AutoNomor();
       
    }//GEN-LAST:event_table_clientMouseClicked

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Client");
        model.addColumn("Company Name");
        model.addColumn("Staff Name");
        model.addColumn("Email");
        model.addColumn("Phone");
        model.addColumn("Addres");
        
        try {
            String sql = "select * from client where id_client like '%" + txtCari.getText() + "%' "+ "OR company_name like '%" +txtCari.getText() + "%'     "+ "OR staff_name like '%" +txtCari.getText() + "%'     "+ "OR email like '%" +txtCari.getText() + "%'    "+ "OR phone like '%" +txtCari.getText() + "%'   "+ "OR addres like '%" +txtCari.getText() + "%' ";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                model.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6)});
            }
            table_client.setModel(model);
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_btnCariActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
           makePreview("client");
  

    }//GEN-LAST:event_jLabel6MouseClicked

    private void headMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headMouseClicked
        // TODO add your handling code here:
                 mainMenu fs = new mainMenu();
        fs.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_headMouseClicked

    
      private void makePreview (String vName){
        try {
            String gambarkop = getClass().getResource("/assets/tritanu_head.png").toString();
            String sql = "SELECT * FROM client";
            java.sql.Connection conn=(Connection)config.configDB();        
            String locFile = "src/Report/";
            String namaFile = locFile + vName + ".jasper";
            HashMap parameter = new HashMap();
            parameter.put("kop", gambarkop);
            File report_file = new File (namaFile);
            JasperReport jasperReport = (JasperReport) JRLoader.loadObject(report_file.getPath());
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameter, conn);
            JasperViewer.viewReport(jasperPrint, false );
            JasperViewer.setDefaultLookAndFeelDecorated(true);
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
      }
    
    private void kosong(){
        txt_id.setText(null);
        company_name.setText(null);
        staff_name.setText(null);
        email.setText(null);  
        phone.setText(null);
        addres.setText(null); 
        txtCari.setText(null);
        
    }
    
    
    private void table_client(){
        // membuat tampilan model tabel
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Client");
        model.addColumn("Company Name");
        model.addColumn("Staff Name");
        model.addColumn("Email");
        model.addColumn("Phone");
        model.addColumn("Addres");
        //menampilkan data database kedalam tabel
        try {
            int no=1;
            String sql = "select * from client";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                model.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6)});
            }
            table_client.setModel(model);
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        save.setEnabled(true);
        edit.setEnabled(false);
        delete.setEnabled(false);
    }
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Client().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CLEAR;
    private javax.swing.JLabel NAME;
    private javax.swing.JLabel NAME1;
    private javax.swing.JLabel NAME3;
    private javax.swing.JTextArea addres;
    private javax.swing.JButton btnCari;
    private javax.swing.JTextField company_name;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JTextField email;
    private javax.swing.JLabel head;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField phone;
    private javax.swing.JButton save;
    private javax.swing.JTextField staff_name;
    private javax.swing.JTable table_client;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txt_id;
    // End of variables declaration//GEN-END:variables
}
